#  FILE:      nate1-graph.cg
#  CONTENT:   ION contact graph commands file
#  FOR:       ionadmin
#  BUILDER:   ION Configuration Editor
#  NETWORK:   nate1-ion    [ION Test nate problem]
#  DATE:      2022-07-25T13:50
#
#  CONTACT_REL_REL_TIME
#  [1]                relative start time : 0 (secs) 
#  [2]                 relative stop time : 50000000 (secs) 
#  [3]                        source node : 1000  
#  [4]                   destination node : 1001  
#  [5]             transmission data rate : 0 (bytes per sec) 
#  [6]                 contact confidence : 1 (fraction) 
a contact +0  +50000000  1000  1001  0  1
#
#  CONTACT_REL_REL_TIME
#  [1]                relative start time : 0 (secs) 
#  [2]                 relative stop time : 50000000 (secs) 
#  [3]                        source node : 1001  
#  [4]                   destination node : 1000  
#  [5]             transmission data rate : 0 (bytes per sec) 
#  [6]                 contact confidence : 1 (fraction) 
a contact +0  +50000000  1001  1000  0  1
#
#  CONTACT_REL_REL_TIME
#  [1]                relative start time : 0 (secs) 
#  [2]                 relative stop time : 50000000 (secs) 
#  [3]                        source node : 1000  
#  [4]                   destination node : 1002  
#  [5]             transmission data rate : 0 (bytes per sec) 
#  [6]                 contact confidence : 1 (fraction) 
a contact +0  +50000000  1000  1002  0  1
#
#  CONTACT_REL_REL_TIME
#  [1]                relative start time : 0 (secs) 
#  [2]                 relative stop time : 50000000 (secs) 
#  [3]                        source node : 1002  
#  [4]                   destination node : 1000  
#  [5]             transmission data rate : 0 (bytes per sec) 
#  [6]                 contact confidence : 1 (fraction) 
a contact +0  +50000000  1002  1000  0  1
#
#  RANGE_REL_REL_TIME
#  [1]                relative start time : 0 (secs) 
#  [2]                 relative stop time : 50000000 (secs) 
#  [3]                           one node : 1000  
#  [4]                         other node : 1001  
#  [5]              transmission distance : 1 (light secs) 
a range +0  +50000000  1000  1001  1
#
#  RANGE_REL_REL_TIME
#  [1]                relative start time : 0 (secs) 
#  [2]                 relative stop time : 50000000 (secs) 
#  [3]                           one node : 1001  
#  [4]                         other node : 1000  
#  [5]              transmission distance : 1 (light secs) 
a range +0  +50000000  1001  1000  1
#
#  RANGE_REL_REL_TIME
#  [1]                relative start time : 0 (secs) 
#  [2]                 relative stop time : 50000000 (secs) 
#  [3]                           one node : 1000  
#  [4]                         other node : 1002  
#  [5]              transmission distance : 1 (light secs) 
a range +0  +50000000  1000  1002  1
#
#  RANGE_REL_REL_TIME
#  [1]                relative start time : 0 (secs) 
#  [2]                 relative stop time : 50000000 (secs) 
#  [3]                           one node : 1002  
#  [4]                         other node : 1000  
#  [5]              transmission distance : 1 (light secs) 
a range +0  +50000000  1002  1000  1
