#!/bin/bash
#
#   bind_ionsurvey.sh
#
# bind sub modules together for complete ionsurvey.js
#
# inputs:  ../src
#
# outputs: ../bin/ionsurvey.js
#
# author: Dave Hanks
#

src=../src
autosrc=../src/auto
bin=../bin

echo "Binding together ionsurvey.js"

echo "#!/usr/bin/env node" > $bin/ionsurvey.js
echo "// THIS FILE IS AUTOMATICALLY GENERATED DURING THE BUILD PROCESS"   >>$bin/ionsurvey.js
echo "// SEE THE MAKE SCRIPT FOR WHICH SOURCE FILES ARE USED TO BUILD IT" >>$bin/ionsurvey.js

cat $src/ionsurvey_main.js      >> $bin/ionsurvey.js
cat $autosrc/ionloader-auto.js  >> $bin/ionsurvey.js
cat $autosrc/checkion-auto.js   >> $bin/ionsurvey.js
cat $autosrc/appfunc-auto.js    >> $bin/ionsurvey.js
cat $autosrc/clone-auto.js      >> $bin/ionsurvey.js
cat $autosrc/ionfunc-auto.js    >> $bin/ionsurvey.js
cat $src/utilfunc.js            >> $bin/ionsurvey.js

chmod +x  $bin/ionsurvey.js
