#!/bin/bash
#
#   bind_checkdtn.sh
#
# bind sub modules together for complete checkdtn.js
#
# inputs:  ../src
#
# outputs: ../bin/checkdtn.js
#
# author: Rick Borgen
#
echo "Binding together checkdtn.js"

src=../src
bin=../bin

echo "#!/usr/bin/env node" > $bin/checkdtn.js
echo "// THIS FILE IS AUTOMATICALLY GENERATED DURING THE BUILD PROCESS"   >> $bin/checkdtn.js
echo "// SEE THE MAKE SCRIPT FOR WHICH SOURCE FILES ARE USED TO BUILD IT" >> $bin/checkdtn.js

cat $src/checkdtn_main.js  >> $bin/checkdtn.js
cat $src/netloader.js      >> $bin/checkdtn.js
cat $src/checknet.js       >> $bin/checkdtn.js

chmod +x  $bin/checkdtn.js
