#!/bin/bash
#
#   bind_dtn2ion.sh
#
# bind sub modules together for complete dtn2ion.js
#
# inputs:  ../src
#
# outputs: ../bin/dtn2ion.js
#
# authors: Rick Borgen, Dave Hanks
#
src=../src
autosrc=../src/auto
bin=../bin

echo "Binding together dtn2ion.js"

echo "#!/usr/bin/env node" > $bin/dtn2ion.js
echo "// THIS FILE IS AUTOMATICALLY GENERATED DURING THE BUILD PROCESS"   >> $bin/dtn2ion.js
echo "// SEE THE MAKE SCRIPT FOR WHICH SOURCE FILES ARE USED TO BUILD IT" >> $bin/dtn2ion.js

cat $src/dtn2ion_main.js       >> $bin/dtn2ion.js
cat $autosrc/netloader-auto.js >> $bin/dtn2ion.js
cat $autosrc/checknet-auto.js  >> $bin/dtn2ion.js
cat $autosrc/buildion-auto.js  >> $bin/dtn2ion.js
cat $autosrc/appfunc-auto.js   >> $bin/dtn2ion.js
cat $autosrc/clone-auto.js     >> $bin/dtn2ion.js
cat $autosrc/getfunc-auto.js   >> $bin/dtn2ion.js
cat $autosrc/makeobj-auto.js   >> $bin/dtn2ion.js
cat $src/savemodel.js          >> $bin/dtn2ion.js
cat $src/utilfunc.js           >> $bin/dtn2ion.js

chmod +x $bin/dtn2ion.js
