#!/bin/bash
#
#   bind_ionconfig.sh
#
# bind sub modules together for complete ionconfig.js
#
# inputs:  ../src
#
# outputs: ../bin/ionconfig.js
#
# authors: Rick Borgen, Dave Hanks
#

src=../src
autosrc=../src/auto
bin=../bin

echo "Binding together ionconfig.js"

echo "#!/usr/bin/env node" > $bin/ionconfig.js
echo "// THIS FILE IS AUTOMATICALLY GENERATED DURING THE BUILD PROCESS"   >>$bin/ionconfig.js
echo "// SEE THE MAKE SCRIPT FOR WHICH SOURCE FILES ARE USED TO BUILD IT" >>$bin/ionconfig.js

cat $src/ionconfig_main.js      >> $bin/ionconfig.js
cat $autosrc/ionloader-auto.js  >> $bin/ionconfig.js
cat $autosrc/checkion-auto.js   >> $bin/ionconfig.js
cat $autosrc/appfunc-auto.js    >> $bin/ionconfig.js
cat $autosrc/clone-auto.js      >> $bin/ionconfig.js
cat $autosrc/ionfunc-auto.js    >> $bin/ionconfig.js
cat $src/allconfigs.js          >> $bin/ionconfig.js
cat $src/utilfunc.js            >> $bin/ionconfig.js

chmod +x  $bin/ionconfig.js
