#!/bin/bash
#
#   bind_checkdtn.sh
#
# bind sub modules together for complete checkdtn.js
#
# inputs:  ../src
#
# outputs: ../bin/checkdtn.js
#
# author: Rick Borgen
#
echo "Binding together checkdtn.js"

src=../src
src2=../src/auto
bin=../bin

echo "#!/usr/bin/env node" > $bin/checkdtn.js
echo "// THIS FILE IS AUTOMATICALLY GENERATED DURING THE BUILD PROCESS"   >> $bin/checkdtn.js
echo "// SEE THE MAKE SCRIPT FOR WHICH SOURCE FILES ARE USED TO BUILD IT" >> $bin/checkdtn.js

cat $src/checkdtn_main.js  >> $bin/checkdtn.js
cat $src/netloader.js      >> $bin/checkdtn.js
cat $src/checknet.js       >> $bin/checkdtn.js
cat $src/utilfunc.js       >> $bin/checkdtn.js

chmod +x  $bin/checkdtn.js

echo "Binding together checkdtn-x.js"

echo "#!/usr/bin/env node" > $bin/checkdtn-x.js
echo "// THIS FILE IS AUTOMATICALLY GENERATED DURING THE BUILD PROCESS"   >> $bin/checkdtn-x.js
echo "// SEE THE MAKE SCRIPT FOR WHICH SOURCE FILES ARE USED TO BUILD IT" >> $bin/checkdtn-x.js

cat $src/checkdtn_main.js  >> $bin/checkdtn-x.js
cat $src2/netloader-x.js   >> $bin/checkdtn-x.js
cat $src2/checknet-x.js    >> $bin/checkdtn-x.js
cat $src2/appfunc-x.js     >> $bin/checkdtn-x.js
cat $src/utilfunc.js       >> $bin/checkdtn-x.js

chmod +x  $bin/checkdtn-x.js
