#!/bin/bash
#
#   bind_ionsurvey.sh
#
# bind sub modules together for complete ionsurvey.js
#
# inputs:  ../src
#
# outputs: ../bin/ionsurvey.js
#
# author: Dave Hanks
#

src=../src
src2=../src/auto
bin=../bin

echo "Binding together ionsurvey.js"
echo "#!/usr/bin/env node" > $bin/ionsurvey.js
echo "// THIS FILE IS AUTOMATICALLY GENERATED DURING THE BUILD PROCESS"   >>$bin/ionsurvey.js
echo "// SEE THE MAKE SCRIPT FOR WHICH SOURCE FILES ARE USED TO BUILD IT" >> $bin/ionsurvey.js

cat $src/ionsurvey_main.js >> $bin/ionsurvey.js
cat $src/ionloader.js      >> $bin/ionsurvey.js
cat $src/checkion.js       >> $bin/ionsurvey.js
cat $src/appfunc.js        >> $bin/ionsurvey.js
cat $src/clone.js          >> $bin/ionsurvey.js
cat $src/ionfunc.js        >> $bin/ionsurvey.js
cat $src/utilfunc.js       >> $bin/ionsurvey.js

chmod +x  $bin/ionsurvey.js

echo "Binding together ionsurvey-x.js"

echo "#!/usr/bin/env node" > $bin/ionsurvey-x.js
echo "// THIS FILE IS AUTOMATICALLY GENERATED DURING THE BUILD PROCESS"   >>$bin/ionsurvey-x.js
echo "// SEE THE MAKE SCRIPT FOR WHICH SOURCE FILES ARE USED TO BUILD IT" >> $bin/ionsurvey-x.js

cat $src/ionsurvey-x_main.js >> $bin/ionsurvey-x.js
cat $src2/ionloader-x.js     >> $bin/ionsurvey-x.js
cat $src2/checkion-x.js      >> $bin/ionsurvey-x.js
cat $src2/appfunc-x.js       >> $bin/ionsurvey-x.js
cat $src2/clone-x.js         >> $bin/ionsurvey-x.js
cat $src2/ionfunc-x.js       >> $bin/ionsurvey-x.js
cat $src/utilfunc.js         >> $bin/ionsurvey-x.js

chmod +x  $bin/ionsurvey-x.js
