#!/bin/bash
#
#   bind_checkdtn.sh
#
# bind sub modules together for complete checkdtn.js
#
# inputs:  ../src ../src/auto
#
# outputs: ../bin/checkdtn.js
#
# authors: Rick Borgen, Dave Hanks
#

src=../src
autosrc=../src/auto
bin=../bin

echo "Binding together checkdtn.js"

echo "#!/usr/bin/env node" > $bin/checkdtn.js
echo "// THIS FILE IS AUTOMATICALLY GENERATED DURING THE BUILD PROCESS"   >> $bin/checkdtn.js
echo "// SEE THE MAKE SCRIPT FOR WHICH SOURCE FILES ARE USED TO BUILD IT" >> $bin/checkdtn.js

cat $src/checkdtn_main.js        >> $bin/checkdtn.js
cat $autosrc/netloader-auto.js   >> $bin/checkdtn.js
cat $autosrc/checknet-auto.js    >> $bin/checkdtn.js
cat $autosrc/appfunc-auto.js     >> $bin/checkdtn.js
cat $src/utilfunc.js             >> $bin/checkdtn.js

chmod +x  $bin/checkdtn.js
